name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          if: ${{ github.event_name == 'push' }} and ${{ !contains(join(github.event.commits.*.message, ', '), '#skip') }}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: shrouded-stream-54830
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://shrouded-stream-54830.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - name: Success message to Slack on deploy
        if: ${{ job.status == 'success' }}
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Deploy occurred!\"}},{\"type\":\"divider\"},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Status success! :star::star::star::star:\"}}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
